#
# perfSONAR Testbed System Configuration
#

# What testbed configuration will be used.  (See testbeds/*.yaml.)
testbed: internet2


# TODO: This can probably go away once it's all Ansible.
perfsonar-repo: http://software.internet2.edu/rpms/el7/x86_64/latest/packages/perfSONAR-repo-0.10-1.noarch.rpm


defaults:

  box: centos/7
  cpus: 4
  memory: 4096

  # List of meshes that pSConfig should use
  meshes: [
    "http://mca-nightly.grnoc.iu.edu/pub/config/testbed-nightly"
  ]

  # Rebuild nightly
  rebuild: false

  repository: production

  # Set true to leave a placeholder for the host in the addressing scheme
  skip: false


hosts:

  tb-el7-patch:
    repository: nightly-patch

  tb-el7-patch-dr:
    repository: nightly-patch
    rebuild: true


  tb-el7-minor:
    repository: nightly-minor

  tb-el7-minor-dr:
    repository: nightly-minor
    rebuild: true


  tb-el7-staging:
    repository: staging

  tb-el7-staging-dr:
    repository: staging
    rebuild: true


  tb-el7-prod:
    repository: production

  tb-el7-prod-dr:
    repository: production
    rebuild: true
